/// <reference path="account.ts"/>
/// <reference path="bigmap.ts"/>
/// <reference path="block.ts" />
/// <reference path="commitment.ts" />
/// <reference path="contract.ts"/>
/// <reference path="cycle.ts"/>
/// <reference path="delegate.ts"/>
/// <reference path="head.ts"/>
/// <reference path="operation.ts"/>
/// <reference path="protocol.ts"/>
/// <reference path="quote.ts"/>
/// <reference path="reward.ts"/>
/// <reference path="right.ts"/>
/// <reference path="software.ts"/>
/// <reference path="statistics.ts"/>
/// <reference path="voting.ts"/>
